//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCS_AECIS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DCS_AECIS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude.
        /// </summary>
        public static string altitude {
            get {
                return ResourceManager.GetString("altitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string app_about {
            get {
                return ResourceManager.GetString("app_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Altitude Change Speed.
        /// </summary>
        public static string camera_alt_change_speed {
            get {
                return ResourceManager.GetString("camera_alt_change_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Data.
        /// </summary>
        public static string camera_data {
            get {
                return ResourceManager.GetString("camera_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Movement Speed.
        /// </summary>
        public static string camera_movement_speed {
            get {
                return ResourceManager.GetString("camera_movement_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Rotation Speed.
        /// </summary>
        public static string camera_rotation_speed {
            get {
                return ResourceManager.GetString("camera_rotation_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string connect {
            get {
                return ResourceManager.GetString("connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string data_port {
            get {
                return ResourceManager.GetString("data_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string disconnect {
            get {
                return ResourceManager.GetString("disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ WIP ] Use Mouse/Keyboard.
        /// </summary>
        public static string enable_mouse_keyboard {
            get {
                return ResourceManager.GetString("enable_mouse_keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental / Work In Progress Functions:
        ///——————————————————
        ///These functions are still being worked on, 
        ///and it might be removed later.
        ///If they do not work properly, enabling 
        ///these functions could have unexpected 
        ///effect on your DCS World game (although, 
        ///if so, restart DCS will fix it) or to your 
        ///Mouse/Keyboard input performance 
        ///(since it utilizes a low level mouse hook, 
        ///which may not be properly unload and 
        ///disposed if an unhandled exception occured)..
        /// </summary>
        public static string experiment_functions_tooltip_head {
            get {
                return ResourceManager.GetString("experiment_functions_tooltip_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Feedback.
        /// </summary>
        public static string force_feedback {
            get {
                return ResourceManager.GetString("force_feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HDG.
        /// </summary>
        public static string heading {
            get {
                return ResourceManager.GetString("heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string high {
            get {
                return ResourceManager.GetString("high", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string low {
            get {
                return ResourceManager.GetString("low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PITCH.
        /// </summary>
        public static string pitch {
            get {
                return ResourceManager.GetString("pitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROLL.
        /// </summary>
        public static string roll {
            get {
                return ResourceManager.GetString("roll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep AECIS Topmost.
        /// </summary>
        public static string window_topmost {
            get {
                return ResourceManager.GetString("window_topmost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string zoom {
            get {
                return ResourceManager.GetString("zoom", resourceCulture);
            }
        }
    }
}
